version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"  
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  microsservices:
    image: microsservices
    build:
      context: .
      dockerfile: Microsservices/Dockerfile
    depends_on:
      - catalogdb
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  basket.api:
    build:
      context: ./Basket.API
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:RedisConnection=redis:6379"
    depends_on:
      - redis 
volumes:
  mongo_data:
